ASPShoppingCart2022/Models/CartItem.cs
using System.ComponentModel.DataAnnotations;

namespace ASPShoppingCart2022.Models
{
    public class CartItem
    {
        [Display(Name = "Název položky")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Počet kusů")]
        [Range(1, 100)]
        [Required]
        public int Amount { get; set; }
        [Display(Name = "Jednotková cena")]
        [Required]
        public double UnitPrice { get; set; }
    }
}

ASPShoppingCart2022/Pages/Add.cshtml.cs
using Microsoft.AspNetCore.Http;
using ASPShoppingCart2022.Models;
using ASPShoppingCart2022.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPShoppingCart2022.Pages
{
    public class AddModel : PageModel
    {
        public CartItem Item { get; set; }
        private List<CartItem> Cart { get; set; } = new List<CartItem>();

        public string ItemName { get; set; }
        public int ItemAmount { get; set; }
        public float ItemUnitPrice { get; set; }

        // Services
        private readonly ISessionStorage<CartItem> _sessionStorage;

        public AddModel(ISessionStorage<CartItem> sessionStorage)
        {
            _sessionStorage = sessionStorage;
        }

        public ActionResult OnPost()
        {
            try
            {
                ItemName = Request.Form["item-name"].ToString();
                ItemAmount = Int16.Parse(Request.Form["item-amount"]);
                ItemUnitPrice = float.Parse(Request.Form["item-price"]);
            }
            catch
            {
                return RedirectToPage("Index", new { alertMessege = "Položka nebyla přidána, data nejsou validní." });
            }

            Item = new CartItem();
            Item.Name = ItemName;
            Item.Amount = ItemAmount;
            Item.UnitPrice = ItemUnitPrice;

            if (HttpContext.Session.GetString("cart") != null)
            {
                Cart = (HttpContext.Session.Get<List<CartItem>>("cart"));
                Cart.Add(Item);
            }
            else
            {
                Cart.Add(Item);
            }

            HttpContext.Session.Set<List<CartItem>>("cart", Cart);

            return RedirectToPage("Index", new { cartItem = Item });
        }
    }
}

ASPShoppingCart2022/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ASPShoppingCart2022.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ASPShoppingCart2022/Pages/Index.cshtml.cs
using ASPShoppingCart2022.Models;
using ASPShoppingCart2022.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Session;
using System.ComponentModel;

namespace ASPShoppingCart2022.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public List<CartItem> Cart { get; set; } = new List<CartItem>();
        public string AlertMessege;

        // Services
        private readonly ISessionStorage<CartItem> _sessionStorage;

        public IndexModel(ILogger<IndexModel> logger, ISessionStorage<CartItem> sessionStorage)
        {
            _logger = logger;
            _sessionStorage = sessionStorage;
        }

        public IActionResult OnGet(CartItem cartItem, string alertMessege)
        {
            if (HttpContext.Session.GetString("cart") != null)
            {
                Cart = (HttpContext.Session.Get<List<CartItem>>("cart"));
            }

            if (alertMessege != null)
            {
                AlertMessege = alertMessege;
            }

            return Page();
        }

        public IActionResult OnGetClear()
        {
            HttpContext.Session.Remove("cart");
            return RedirectToPage("Index", new { alertMessege = "Košík byl vyprázdněn." });
        }

        public IActionResult OnGetDelete(int val)
        {
            Cart = (HttpContext.Session.Get<List<CartItem>>("cart"));
            Cart.RemoveAt(val);
            HttpContext.Session.Set<List<CartItem>>("cart", Cart);
            return RedirectToPage("Index", new { alertMessege = "Předmět byl z košíku smazán." });
        }
    }
}

ASPShoppingCart2022/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPShoppingCart2022.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ASPShoppingCart2022/Pages/Add.cshtml
@page
@model ASPShoppingCart2022.Pages.AddModel
@{
}
<form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Item.Name"></label>
        <input name="item-name" id="item-name" type="text" class="form-control" asp-for="Item.Name" aria-describedby="nameHelp" placeholder="Židlička">
        <span asp-validation-for="Item.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Amount"></label>
        <input name="item-amount" id="item-amount" type="number" class="form-control" asp-for="Item.Amount" aria-describedby="nameHelp" placeholder="1">
        <span asp-validation-for="Item.Amount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.UnitPrice"></label>
        <input name="item-price" id="item-price" type="text" class="form-control" asp-for="Item.UnitPrice" aria-describedby="nameHelp" placeholder="100">
        <span asp-validation-for="Item.UnitPrice" class="text-danger"></span>
    </div>
    <div>
        <button type="submit" class="btn btn-primary">Přidat</button>
        <a asp-page="./Index" class="btn btn-secondary">Zpět</a>
    </div>
</form>

ASPShoppingCart2022/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>Nákupní košík</h1>
@if (Model.AlertMessege != null)
{
    <div class="alert alert-danger" role="alert">
        @Model.AlertMessege
    </div>
}
<div class="mt-1">
    <a class="btn btn-danger" asp-page-handler="Clear">Vymazat</a>
</div>
@if (Model.Cart.Count == 0)
            {
    <p>Košík je prázdný.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Zboží</th>
                <th>Počet kusů</th>
                <th>Jednotková cena</th>
                <th>Cena</th>
                <th>Akce</th>
            </tr>
        </thead>
        <tbody>
            @{
                int x = 0;
            }
                @foreach(var item in Model.Cart)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Amount</td>
                        <td>@item.UnitPrice</td>
                        <td>@(item.UnitPrice * item.Amount)</td>
                        <td>
                            <a class="btn btn-danger btn-sm" asp-page-handler="Delete" asp-route-val="@x">Odstranit</a>
                        </td>
                    </tr>
                    x++;
            }
                    </tbody>
                </table>
            }
<div>
    <a asp-page="./Add" class="btn btn-primary">Přidat novou položku</a>
</div>

ASPShoppingCart2022/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPShoppingCart2022</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPShoppingCart2022.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ASPShoppingCart2022</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASPShoppingCart2022 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>